// ================= SAFE PARSERS =================

int parseInt(dynamic value) {
  if (value == null) return 0;
  if (value is int) return value;
  if (value is double) return value.toInt();
  if (value is String) return int.tryParse(value) ?? 0;
  return 0;
}

String parseString(dynamic value) {
  return value?.toString() ?? "";
}

// ================= MAIN MODEL =================

class KeyModel {
  final bool success;
  final KeyData data;

  KeyModel({
    required this.success,
    required this.data,
  });

  factory KeyModel.fromJson(Map<String, dynamic> json) {
    return KeyModel(
      success: json['success'] ?? false,
      data: KeyData.fromJson(json['data'] ?? {}),
    );
  }
}

// ================= DATA =================

class KeyData {
  final KeySummary summary;
  final List<KeyItem> keys;
  final Pagination pagination;

  KeyData({
    required this.summary,
    required this.keys,
    required this.pagination,
  });

  factory KeyData.fromJson(Map<String, dynamic> json) {
    return KeyData(
      summary: KeySummary.fromJson(json['summary'] ?? {}),
      keys: (json['keys'] as List? ?? [])
          .map((e) => KeyItem.fromJson(e))
          .toList(),
      pagination: Pagination.fromJson(json['pagination'] ?? {}),
    );
  }
}

// ================= SUMMARY =================

class KeySummary {
  final int totalKeys;
  final int available;
  final int assigned;
  final int refunded;
  final int expired;

  KeySummary({
    required this.totalKeys,
    required this.available,
    required this.assigned,
    required this.refunded,
    required this.expired,
  });

  factory KeySummary.fromJson(Map<String, dynamic> json) {
    return KeySummary(
      totalKeys: parseInt(json['total_keys']),
      available: parseInt(json['available']),
      assigned: parseInt(json['assigned']),
      refunded: parseInt(json['refunded']),
      expired: parseInt(json['expired']),
    );
  }
}

// ================= KEY ITEM =================

class KeyItem {
  final String id;
  final String keyCode;
  final String status;
  final String displayStatus;
  final String validFrom;
  final String validTo;
  final int daysUntilExpiry;
  final GeneratedBy generatedBy;
  final String createdAt;
  final Assignment assignment;

  KeyItem({
    required this.id,
    required this.keyCode,
    required this.status,
    required this.displayStatus,
    required this.validFrom,
    required this.validTo,
    required this.daysUntilExpiry,
    required this.generatedBy,
    required this.createdAt,
    required this.assignment,
  });

  factory KeyItem.fromJson(Map<String, dynamic> json) {
    return KeyItem(
      id: parseString(json['id']),
      keyCode: parseString(json['key_code']),
      status: parseString(json['status']),
      displayStatus: parseString(json['display_status']),
      validFrom: parseString(json['valid_from']),
      validTo: parseString(json['valid_to']),
      daysUntilExpiry: parseInt(json['days_until_expiry']),
      generatedBy: GeneratedBy.fromJson(json['generated_by'] ?? {}),
      createdAt: parseString(json['created_at']),
      assignment: Assignment.fromJson(json['assignment'] ?? {}),
    );
  }
}

// ================= GENERATED BY =================

class GeneratedBy {
  final String id;
  final String name;
  final String mobile;
  final String email;

  GeneratedBy({
    required this.id,
    required this.name,
    required this.mobile,
    required this.email,
  });

  factory GeneratedBy.fromJson(Map<String, dynamic> json) {
    return GeneratedBy(
      id: parseString(json['_id']),
      name: parseString(json['name']),
      mobile: parseString(json['mobile']),
      email: parseString(json['email']),
    );
  }
}

// ================= ASSIGNMENT =================

class Assignment {
  final String customerName;
  final String customerMobile;
  final String phoneBrand;
  final String phoneModel;
  final String assignedAt;

  Assignment({
    required this.customerName,
    required this.customerMobile,
    required this.phoneBrand,
    required this.phoneModel,
    required this.assignedAt,
  });

  factory Assignment.fromJson(Map<String, dynamic> json) {
    return Assignment(
      customerName: parseString(json['customer_name']),
      customerMobile: parseString(json['customer_mobile']),
      phoneBrand: parseString(json['phone_brand']),
      phoneModel: parseString(json['phone_model']),
      assignedAt: parseString(json['assigned_at']),
    );
  }
}

// ================= PAGINATION =================

class Pagination {
  final int page;
  final int limit;
  final int total;
  final int pages;

  Pagination({
    required this.page,
    required this.limit,
    required this.total,
    required this.pages,
  });

  factory Pagination.fromJson(Map<String, dynamic> json) {
    return Pagination(
      page: parseInt(json['page']),
      limit: parseInt(json['limit']),
      total: parseInt(json['total']),
      pages: parseInt(json['pages']),
    );
  }
}
