// keys_model.dart

// =================== HELPERS ===================

String parseString(dynamic v) => v?.toString() ?? "";

int parseInt(dynamic v) {
  if (v == null) return 0;
  if (v is int) return v;
  return int.tryParse(v.toString()) ?? 0;
}

// =================== ROOT ===================

class KeysResponse {
  final bool success;
  final KeysData data;

  KeysResponse({
    required this.success,
    required this.data,
  });

  factory KeysResponse.fromJson(Map<String, dynamic> json) {
    return KeysResponse(
      success: json["success"] ?? false,
      data: KeysData.fromJson(json["data"] ?? {}),
    );
  }
}

// =================== DATA ===================

class KeysData {
  final KeysSummary summary;
  final List<KeyItem> keys;
  final Pagination pagination;

  KeysData({
    required this.summary,
    required this.keys,
    required this.pagination,
  });

  factory KeysData.fromJson(Map<String, dynamic> json) {
    return KeysData(
      summary: KeysSummary.fromJson(json["summary"] ?? {}),
      keys: (json["keys"] as List? ?? [])
          .map((e) => KeyItem.fromJson(e))
          .toList(),
      pagination: Pagination.fromJson(json["pagination"] ?? {}),
    );
  }
}

// =================== SUMMARY ===================

class KeysSummary {
  final int totalKeys;
  final int available;
  final int assigned;
  final int refunded;
  final int expired;

  KeysSummary({
    required this.totalKeys,
    required this.available,
    required this.assigned,
    required this.refunded,
    required this.expired,
  });

  factory KeysSummary.fromJson(Map<String, dynamic> json) {
    return KeysSummary(
      totalKeys: parseInt(json["total_keys"]),
      available: parseInt(json["available"]),
      assigned: parseInt(json["assigned"]),
      refunded: parseInt(json["refunded"]),
      expired: parseInt(json["expired"]),
    );
  }
}

// =================== KEY ITEM ===================

class KeyItem {
  final String id;
  final String keyCode;
  final String status;
  final String displayStatus;
  final String validFrom;
  final String validTo;
  final int daysUntilExpiry;
  final GeneratedBy generatedBy;
  final String createdAt;

  KeyItem({
    required this.id,
    required this.keyCode,
    required this.status,
    required this.displayStatus,
    required this.validFrom,
    required this.validTo,
    required this.daysUntilExpiry,
    required this.generatedBy,
    required this.createdAt,
  });

  factory KeyItem.fromJson(Map<String, dynamic> json) {
    return KeyItem(
      id: parseString(json["id"]),
      keyCode: parseString(json["key_code"]),
      status: parseString(json["status"]),
      displayStatus: parseString(json["display_status"]),
      validFrom: parseString(json["valid_from"]),
      validTo: parseString(json["valid_to"]),
      daysUntilExpiry: parseInt(json["days_until_expiry"]),
      generatedBy: GeneratedBy.fromJson(json["generated_by"] ?? {}),
      createdAt: parseString(json["created_at"]),
    );
  }
}

// =================== GENERATED BY ===================

class GeneratedBy {
  final String id;
  final String name;
  final String mobile;
  final String email;

  GeneratedBy({
    required this.id,
    required this.name,
    required this.mobile,
    required this.email,
  });

  factory GeneratedBy.fromJson(Map<String, dynamic> json) {
    return GeneratedBy(
      id: parseString(json["_id"]),
      name: parseString(json["name"]),
      mobile: parseString(json["mobile"]),
      email: parseString(json["email"]),
    );
  }
}

// =================== PAGINATION ===================

class Pagination {
  final int page;
  final int limit;
  final int total;
  final int pages;

  Pagination({
    required this.page,
    required this.limit,
    required this.total,
    required this.pages,
  });

  factory Pagination.fromJson(Map<String, dynamic> json) {
    return Pagination(
      page: parseInt(json["page"]),
      limit: parseInt(json["limit"]),
      total: parseInt(json["total"]),
      pages: parseInt(json["pages"]),
    );
  }
}
